# Generated by Django 5.2.15 on 2026-07-27 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_payment_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='balance',
        ),
    ]
