# Generated by Django 5.2.15 on 2026-08-09 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_user_location_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('threshold_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_quantity_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PendingPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_quantity_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='collection_district',
        ),
        migrations.RemoveField(
            model_name='post',
            name='collection_union',
        ),
        migrations.RemoveField(
            model_name='post',
            name='collection_upazila',
        ),
        migrations.RemoveField(
            model_name='post',
            name='collection_ward',
        ),
        migrations.RemoveField(
            model_name='post',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='post',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='user',
            name='district',
        ),
        migrations.RemoveField(
            model_name='user',
            name='division',
        ),
        migrations.RemoveField(
            model_name='user',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='user',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='user',
            name='union',
        ),
        migrations.RemoveField(
            model_name='user',
            name='upazila',
        ),
        migrations.AddField(
            model_name='bangladeshlocation',
            name='geo_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bangladeshlocation',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bangladeshlocation',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bangladeshlocation',
            name='url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='api.bangladeshlocation'),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='api.bangladeshlocation'),
        ),
        migrations.AlterField(
            model_name='bangladeshlocation',
            name='level',
            field=models.CharField(choices=[('division', 'Division'), ('district', 'District'), ('upazila', 'Upazila'), ('union', 'Union')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='bangladeshlocation',
            constraint=models.UniqueConstraint(fields=('geo_id', 'level'), name='uniq_geo_level'),
        ),
        migrations.AddField(
            model_name='area',
            name='upazilas',
            field=models.ManyToManyField(limit_choices_to={'level': 'upazila'}, related_name='areas', to='api.bangladeshlocation'),
        ),
        migrations.AddField(
            model_name='batch',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='api.area'),
        ),
        migrations.AddField(
            model_name='batch',
            name='deliveryman',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'deliveryman'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batch',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='api.producttype'),
        ),
        migrations.AddField(
            model_name='batch',
            name='union',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='api.bangladeshlocation'),
        ),
        migrations.AddField(
            model_name='batchitem',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.batch'),
        ),
        migrations.AddField(
            model_name='batchitem',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batchitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_items', to='api.order'),
        ),
        migrations.AddField(
            model_name='pendingpool',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='api.area'),
        ),
        migrations.AddField(
            model_name='pendingpool',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='api.producttype'),
        ),
        migrations.AddField(
            model_name='pendingpool',
            name='union',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='api.bangladeshlocation'),
        ),
        migrations.AlterUniqueTogether(
            name='pendingpool',
            unique_together={('area', 'union', 'product_type')},
        ),
    ]
