# Generated by Django 5.2.15 on 2026-08-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_payment_order_payment_paid_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='deliveryman',
        ),
        migrations.RemoveField(
            model_name='order',
            name='picked_up_at',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
