# Generated by Django 5.2.15 on 2026-08-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_otp_failed_attempts_alter_otp_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerbankaccount',
            name='payment_mode',
            field=models.CharField(choices=[('IFT', 'IFT (BRAC to BRAC)'), ('EFT', 'EFT (Inter-bank)'), ('RTGS', 'RTGS (Urgent Inter-bank)'), ('MFS', 'MFS (bKash / Mobile)')], default='EFT', max_length=10),
        ),
    ]
