# Generated by Django 5.2.15 on 2026-08-16 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_review_farmer_and_title(apps, schema_editor):
    Review = apps.get_model('api', 'Review')
    for review in Review.objects.select_related('post').iterator():
        changed = False
        if review.farmer_id is None and review.post_id is not None:
            review.farmer_id = review.post.farmer_id
            changed = True
        if not review.post_title and review.post_id is not None:
            review.post_title = review.post.title or ''
            changed = True
        if changed:
            review.save(update_fields=['farmer', 'post_title'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_corpnet_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='farmer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'farmer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='post_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='review',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='api.post'),
        ),
        migrations.RunPython(backfill_review_farmer_and_title, migrations.RunPython.noop),
    ]
