# Generated by Django 5.2.15 on 2026-08-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_batch_payment_verified_order_advance_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='sender_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='uddokta_invoice_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('sslcommerz', 'SSLCommerz'), ('bkash', 'bKash'), ('uddoktapay', 'UddoktaPay')], default='bkash', max_length=20),
        ),
    ]
