# Generated by Django 5.2.15 on 2026-08-19 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_payment_sender_number_payment_uddokta_invoice_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='est_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity_type',
            field=models.CharField(choices=[('kg', 'Per KG'), ('piece', 'Per Piece')], default='kg', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='settlement_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='settlement_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='est_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='quantity_type',
            field=models.CharField(choices=[('kg', 'Per KG'), ('piece', 'Per Piece')], default='kg', help_text="'kg' sells by weight, 'piece' sells by individual unit", max_length=10),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('batch_assigned', 'Batch Assigned'), ('batch_picked_up', 'Batch Picked Up'), ('batch_in_transit', 'Batch In Transit'), ('payment_verified', 'Payment Verified'), ('batch_delivered', 'Batch Delivered'), ('system', 'System')], default='system', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True, default='')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.batch')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
