# Generated by Django 5.2.15 on 2026-08-21 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_order_status_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualbkashpayment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
