# Generated by Django 5.2.15 on 2026-08-21 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_manualbkashpayment_id'),
        ('api', '0020_user_bkash_number'),
    ]

    operations = [
    ]
